### ISSUE TITLE
RTMP video crashes lethe

### ISSUE THREAD

**Issue by ghost** [meew0/Lethe#10]
N-svzoOgDkM for example crashes music bot
rtmp protocol
![error image](https://cloud.githubusercontent.com/assets/2537696/11323903/bedb1c74-9120-11e5-8a18-62b542142549.png)

**Comment by meew0** [comment]
Probably a bug with ytdl. Will look into this

**Comment by meew0** [comment]
I can't make RTMP video work (this is apparently intended in ytdl), so I just made it not crash when attempting it.
