### ISSUE TITLE
Crashing on long videos

### ISSUE THREAD

**Issue by thebitstick** [meew0/Lethe#11]
An easily reproducible bug shows up when adding long videos of more than around 10 minutes.

**Comment by meew0** [comment]
[This 10 hour long video](https://www.youtube.com/watch?v=Vg5TGQKGn6w) successfully added and played for me. Is there any specific video this doesn't work with?

**Comment by meew0** [comment]
Closing this due to insufficient information, if it still happens, I'll reopen it.
