### ISSUE TITLE
crashes when using yt

### ISSUE THREAD

**Issue by nohandtail** [meew0/Lethe#15]
Trying to run this from a cloud (c9.io) after having some problems with windows. Any ideas why this happened? Maybe I installed ffmpeg improperly on the cloud?

The lethe-data.json file doesn't exist! This is not an error.
Bot mention: @120426524829548544
[debug] ready packet took 9ms to process
[debug] ready with 3 servers, 23 channels and 28 users cached.
[debug] removed temporary voice websocket listeners
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn help ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by meew0** [comment]
You don't have ffmpeg installed (or it's installed and not in your PATH). Install it and it should work fine

**Comment by nohandtail** [comment]
Okay, uh I'm not sure how to install it. Could you help me out? I believe the cloud is using ubuntu.

**Comment by nohandtail** [comment]
okay, got it to work for ubuntu 14.04

```
 sudo add-apt-repository ppa:mc3man/trusty-media
 sudo apt-get update
 sudo apt-get install ffmpeg
```
