### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by shotgun2197** [meew0/Lethe#17]
I wanted to test out Lethe and every time I leave it to play audio, I get this error ![error message](http://i.imgur.com/wh3beHL.png). The bot will post the message in the chat after about 5 minutes, keep playing audio for a few seconds and then stop voice chatting all together.

If I can get you any other information, let me know. Maybe it's on my end, but I am not sure.

**Comment by meew0** [comment]
Seems like a network problem, are you sure you have a stable connection?

**Comment by shotgun2197** [comment]
I should, but I would understand if I didn't. I get patches of lag in certain games that nobody else gets. I just assumed it might be on the discord end shutting down the connection. I'll play with it a bit and call it quits if its just me. You can close this for now.

**Comment by meew0** [comment]
It's possible that Discord shuffled you around voice servers in a way that crashed discord.js, but I'd assume connection instability myself. I'll close it, reopen if it happens again
