### ISSUE TITLE
Lack of permission to run @Bot init, while I am the owner of the server

### ISSUE THREAD

**Issue by FFZendikar** [meew0/Lethe#35]

**Comment by meew0** [comment]
If you run the bot, put your own user ID into the "adminIds" section of the lethe-config.json. If you're not, ask the bot maintainer to do so.

**Comment by FFZendikar** [comment]
Not sure where I can find my user ID; not very familiar with code :(

**Comment by meew0** [comment]
Ah, that's a problem. Getting a user ID is quite complicated without the API - I'll just add the user ID to the end of the "you don't have permission" message.

**Comment by meew0** [comment]
You will have to update Lethe for this change to apply, a simple `git pull` in the Lethe folder should be enough.
