### ISSUE TITLE
stray ffmpeg processes

### ISSUE THREAD

**Issue by tycho** [meew0/Lethe#39]
Each time Lethe switches to another track it will leave a stale ffmpeg process around:

```
$ ps fax
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
[...]
lethe      416  2.8  0.1 1279844 61968 ?       Ssl  00:31   0:18 /usr/bin/node lethe.js
lethe    13791  0.1  0.0 475584 20816 ?        Sl   00:32   0:00  \_ ffmpeg -loglevel 0 -i - -f s16le -ar 48000 -ac 2 pipe:1
lethe    29131  0.1  0.0 475340 20644 ?        Sl   00:34   0:00  \_ ffmpeg -loglevel 0 -i - -f s16le -ar 48000 -ac 2 pipe:1
lethe    27834  0.2  0.0 475704 21512 ?        Sl   00:36   0:01  \_ ffmpeg -loglevel 0 -i - -f s16le -ar 48000 -ac 2 pipe:1
lethe    32217  0.7  0.0 475148 20628 ?        Sl   00:42   0:00  \_ ffmpeg -loglevel 0 -i - -f s16le -ar 48000 -ac 2 pipe:1
```

It should be terminating these child processes after the track is done.

**Comment by meew0** [comment]
This should have been fixed in discord.js recently, can you fully update discord.js to the latest indev (`npm install hydrabolt/discord.js#indev`) and see if it still happens?

**Comment by tycho** [comment]
I'm running it out of the git repo, and it does appear to be fixed in the latest tree. Nice to see there's also a lethe-auth.json implemented (I'd written a patch to do that very thing locally).
