### ISSUE TITLE
Windows not playing

### ISSUE THREAD

**Issue by RYGUY722** [meew0/Lethe#40]
I can get the bot to start successfully, and everything seems to be working fine, but whenever I use yt is says that it queued the video and is playing it, but it won't play any audio. Upon using time, it consistently tells me that the video is at 0:00. Nothing unusual is printed to the console at all. I have done everything I can think of and have pretty much memorized certain lines of your readme. Please help?

**Comment by meew0** [comment]
This usually means node-opus is not installed correctly, are you sure you have set up a correct build environment? Try rerunning `npm install node-opus` and see if there are any errors in that output.

**Comment by RYGUY722** [comment]
I figured out what was wrong. I hadn't added FFMPEG to my PATH like a total idiot.
