### ISSUE TITLE
Playlist function doesn't work

### ISSUE THREAD

**Issue by kennethbj82** [meew0/Lethe#41]
The "pl" command seems to not be working. 

"There was an error finding playlist with that id."

I've tested multiple combinations, multiple playlists. Even tried adding "list=..." from the youtube source.

**Comment by meew0** [comment]
Could you show the exact command you used?

**Comment by kennethbj82** [comment]
@kingofthedisco pl PL63F0C78739B09958
@kingofthedisco pl PL7E436F1EC114B001
@kingofthedisco pl PLWRJVI4Oj4IaYIWIpFlnRJ_v_fIaIl6Ey
@kingofthedisco pl PL7BA598CBAF2745D9

Tried those, didn't work, just got the error -> "There was an error finding playlist with that id."

Like stated about, i also tried including list=, even though that makes no sense -> @kingofthedisco pl list=PLWRJVI4Oj4IaYIWIpFlnRJ_v_fIaIl6Ey

**Comment by meew0** [comment]
The third entry `pl PLWRJVI4Oj4IaYIWIpFlnRJ_v_fIaIl6Ey` should work, are you sure that didn't work?

**Comment by kennethbj82** [comment]
BilzToday at 10:40 AM
@kingofthedisco pl PLWRJVI4Oj4IaYIWIpFlnRJ_v_fIaIl6Ey
kingofthediscoToday at 10:40 AM
@Bilz, There was an error finding playlist with that id.

**Comment by Sikksens** [comment]
Have you changed the request url at all? I got this when changing the maxresults option.

**Comment by kennethbj82** [comment]
I've done nothing, it's "straight out the box." Except i've changed a few options in the config file for what is allowed by non-admins. 

Everything else works fine. (I think, not tested everything meticulously)

**Comment by kennethbj82** [comment]
Searching doesn't work either, I suspect it's related to the API. So i tried making a new api-key and throwing that in. Same problem.

If i use the API's explorer on the google dev console site i it seems to work fine, so i'm not sure what it is. 

Also tried adding my ip to the access list, just to make sure it was getting it. 

Still the same.

**Comment by preeefix** [comment]
@kennethbj82 Can you try doing a curl/wget request from the server in question and see if it returns the appropriate response?

Example Request: https://www.googleapis.com/youtube/v3/search?part=snippet&q=taco%20bell&key= `APIKEY`

**Comment by kennethbj82** [comment]
{
 "kind": "youtube#searchListResponse",
 "etag": "\"oqbvhYxBE6fAbRk6m7aLlHf5s1I/o7mMvX-xjNx38aLkYmMf2RVINFM\"",
 "nextPageToken": "CAUQAA",
 "pageInfo": {
  "totalResults": 1000000,
  "resultsPerPage": 5
 },
 "items": [
  {
   "kind": "youtube#searchResult",
   "etag": "\"oqbvhYxBE6fAbRk6m7aLlHf5s1I/POyhyEq6zo94QIQ5S9SRmlZV8Ag\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "TWSOiZrs3oA"
   },
   "snippet": {
    "publishedAt": "2015-03-08T21:32:03.000Z",
    "channelId": "UCpko_-a4wgz2u_DgDgd9fqA",
    "title": "Mexican People Try Taco Bell For The First Time",
    "description": "It's an explosion of flavor!” Check out more awesome videos at BuzzFeedVideo! http://bit.ly/YTbuzzfeedvideo Hace
r El Plan Licensed via Warner Chappell ...",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/TWSOiZrs3oA/default.jpg"
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/TWSOiZrs3oA/mqdefault.jpg"
     },
     "high": {
      "url": "https://i.ytimg.com/vi/TWSOiZrs3oA/hqdefault.jpg"
     }
    },
    "channelTitle": "BuzzFeedVideo",
    "liveBroadcastContent": "none"
   }
  },

etc etc etc etc
So looks fine... i guess. 
Just doesn't work via the bot.

**Comment by skylordjason** [comment]
@kennethbj82 Try pulling the latest commit and adding your API key to the lethe-auth.json file. I don't know if it's a glitch or not but adding it to the auth file fixed that error for me. It seemed the process argument didn't want to work.

**Comment by kennethbj82** [comment]
Putting it in lethe-auth.json made it work. Cheers!

But alas, i guess it's only a work around not a fix.

**Comment by skylordjason** [comment]
OK. I narrowed it down and fixed it in PR #46 

Just a syntax error. Expanded it to an if-else and fixed it.
