### ISSUE TITLE
ENOENT error when opening stream

### ISSUE THREAD

**Issue by skylordjason** [meew0/Lethe#49]
I genuinely have no idea what I've done wrong here. I pulled the latest commit from my personal fork, and this error would appear when attempting to play a video.

I reset and pulled from meew0's, and got the same error. Safe to say I'm lost.

![image](https://cloud.githubusercontent.com/assets/8324596/12466412/0bd73e7a-bf9a-11e5-9e7b-0260b17d1822.png)

I've even gone as far as running it locally in a fresh Ubuntu VM and get the same error.

**Comment by meew0** [comment]
You probably forgot to install ffmpeg.

**Comment by skylordjason** [comment]
You know... Blonde moments suck.

**Comment by meew0** [comment]
Don't worry, it happens to everyone :)
