### ISSUE TITLE
No sound after ytdl update 0.7.10

### ISSUE THREAD

**Issue by macdja38** [meew0/Lethe#51]
Any update to ytdl after 0.7.10 seems to cause the bot to play nothing.

Tested on ubuntu and debian with discord.js 6.1.0 on the indev branch and the master branch.
ffmpeg was updated a few months ago.

**Comment by macdja38** [comment]
This commit seems to be the problem
https://github.com/fent/node-ytdl-core/commit/260737eaddd5e66b38b6c797536c00c653d810ff

**Comment by meew0** [comment]
After some local testing, ytdl 0.7.13 works fine for me. Can you try updating to that and see if it works?

**Comment by macdja38** [comment]
Can confirm, 0.7.13 fixes audio.
