### ISSUE TITLE
Not playing Audio

### ISSUE THREAD

**Issue by Nikos410** [meew0/Lethe#55]
Hey, I just installed the bot, I can queue videos and it shows the "playing message". But I'm not hearing any audio. Basically point 2 under "troubleshooting".

But I'm not really sure which of the steps I have to do under "node-opus build dependencies" in the Beginners guide.
I used option 1, Microsoft's windows-build-tools and it said Visual C++ Build Tools installed and Python 2.7 installed. Because that didn't work I did point 3 under option 2 ("Launch cmd, npm config set msvs_version 2015"). But I still don't get any audio. 
Maybe I didn't understand the instructions correctly, because I have never done anything regarding servers before and english is not my native language.

Yes, I've tried turning it off and on again.

**Comment by meew0** [comment]
Try this: https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules

**Comment by rvddesign** [comment]
This is not working for me either, I've followed the steps (although not sure if done correctly) but it is not playing any audio. What should I test?

The bot itself is saying it's playing, but no sound is heard, also after the video it displays:

> There was a network error during playback! The connection to YouTube may be unstable. Auto-skipping to the next video...
