### ISSUE TITLE
Unable to launch or be installed via npm

### ISSUE THREAD

**Issue by thebitstick** [meew0/Lethe#8]
``` bash
/home/jorge/Downloads/Lethe-master/lethe.js:17
client.on('warn', (m) => console.log('[warn]', m));
                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Is the error I get when trying to run Lethe.js in either node, nodejs, or npm.
I'm wondering what's wrong with it and I hope the solution is simple

**Comment by amishshah** [comment]
It's because you're not using a recent node version, I'm guessing you're on 0.10?

The only way to fix this is by updating your node to the latest version.

**Comment by thebitstick** [comment]
This fixed it.
Ubuntu and Debian have outdated builds of Node.

**Comment by meew0** [comment]
For future reference, here's how to install the latest node 5 on Ubuntu: https://github.com/nodesource/distributions#installation-instructions
