### ISSUE TITLE
Doesn't play on windows

### ISSUE THREAD

**Issue by ghost** [meew0/Lethe#9]
When I queue a song on windows, playback wont start.
I have ffmpeg installed and added to path.
When i start lethe, i have and error saying lethe-data.json is missing, but all commands are working.

**Comment by meew0** [comment]
Apparently, discord.js doesn't play anything on windows but keeps sending "speaking" packets:
https://github.com/hydrabolt/discord.js/blob/master/src/Voice/VoiceConnection.js#L129
![picture](https://cdn.discordapp.com/attachments/81385020756865024/117949079987814404/unknown.png)

**Comment by meew0** [comment]
It looks like the problem was an incorrect installation of node-opus. If anyone else is getting this problem, try installing node-opus manually using `npm install node-opus` and follow the instructions if there are any.
